version: "2"

services:
  traefik:
    image: hypriot/rpi-traefik
    environment:
      - constraint:hypriot.hierarchy==leader
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /dev/null:/traefik.toml
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --docker.endpoint tcp://192.168.200.1:2378 --docker.watch

  whoami:
    image: hypriot/rpi-whoami
    depends_on:
        - traefik
    environment:
      - constraint:hypriot.hierarchy!=leader
      - PORT=8000
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.port=8000"
